---
- hosts: all
  tasks:
    - name: Set ansible_end_user if undefined
      block:
        - name: Get default end user
          ansible.builtin.shell: "realm list | grep -q kerberos && echo $(ls -al /home/ | grep -m1 'domain users' | cut -d ' ' -f3) || id -u -n 1000"
          register: end_user
          changed_when: false
        - name: Set ansible_end_user variable
          ansible.builtin.set_fact:
            ansible_end_user: "{{ end_user.stdout }}"
      rescue:
        - name: Print message
          ansible.builtin.debug:
            msg: 'ansible_end_user variable is undefined'
      when: ansible_end_user is undefined

    - name: Set install_gui_apps if undefined
      block:
        - name: Check if a desktop environment is available
          ansible.builtin.stat:
            path: "/usr/share/xsessions"
          register: xsessions
        - name: Set install_gui_apps variable
          ansible.builtin.set_fact:
            install_gui_apps: "{% if (xsessions.stat.exists) %}True{% else %}False{% endif %}"
      when: install_gui_apps is undefined

- hosts: all
  roles:
    - ecgalaxy.bootstrap
    - ecgalaxy.common_packages
    - ecgalaxy.aws_cli
    - ecgalaxy.ca_certificates
    - ecgalaxy.containers_toolbox
    - ecgalaxy.java_openjdk
    - ecgalaxy.maven
    - ecgalaxy.nodejs
    - ecgalaxy.oracle_instantclient
    - ecgalaxy.php
    - ecgalaxy.task
    - ecgalaxy.terraform

- hosts: all
  roles:
    - role: ecgalaxy.docker
      when: ansible_end_user is undefined

- hosts: all
  roles:
    - role: ecgalaxy.docker
      when: ansible_end_user is defined
  vars:
    docker_users:
      - "{{ ansible_end_user }}"

- hosts: all
  roles:
    - role: ecgalaxy.intellij
      when: install_gui_apps | bool
    - role: ecgalaxy.vscode
      when: install_gui_apps | bool
